create table if not exists public.order_documents (
  id bigint generated by default as identity primary key,

  order_id text not null,
  case_id bigint null,
  order_item_id bigint null,

  type text not null,

  number text not null,

  document_date date not null,

  amount numeric(14, 2) not null default 0,

  reason text null,

  comment text null,

  created_by text null,

  created_at timestamptz not null default now(),

  constraint order_documents_type_check
    check (
      type in (
        'INVOICE',
        'CREDIT_NOTE'
      )
    ),

  constraint order_documents_order_fk
    foreign key (order_id)
    references public.orders(id)
    on delete cascade,

  constraint order_documents_case_fk
    foreign key (case_id)
    references public.order_cases(id)
    on delete set null,

  constraint order_documents_order_item_fk
    foreign key (order_item_id)
    references public.order_items(id)
    on delete set null
);

create index if not exists idx_order_documents_order_id
  on public.order_documents(order_id);

create index if not exists idx_order_documents_case_id
  on public.order_documents(case_id);

create index if not exists idx_order_documents_order_item_id
  on public.order_documents(order_item_id);

create index if not exists idx_order_documents_type
  on public.order_documents(type);

create index if not exists idx_order_documents_document_date
  on public.order_documents(document_date);